from django.conf.urls import url,include
import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^algos/$',csrf_exempt(views.dashboard),name='algos'),
	url(r'^dashboard_metrics/$',csrf_exempt(views.dashboard_metrics),name='dashboard'),
	# url(r'^$',csrf_exempt(views.dashboard),name='dashboard'),
	url(r'^algorithm/$',csrf_exempt(views.algorithm3_),name='algorithm'),
	url(r'^algorithm3/$',csrf_exempt(views.algorithm3),name='algorithm'),
	url(r'^algorithm4/$',csrf_exempt(views.algorithm4),name='algorithm'),
	url(r'^algorithm3_/$',csrf_exempt(views.algorithm3_),name='algorithm'),
	url(r'^strategy/$',csrf_exempt(views.algorithm3_),name='strategy'),
	url(r'^create_similar_strategy/',views.algorithm_clone,name='algorithm_clone'),
	url(r'^copy_algorithm/',views.algorithm_clone2,name='algorithm_clone'),
	url(r'^algorithm_remove/',views.algorithm_remove,name='algorithm_remove'),
	url(r'^is_algorithm_deployed/',views.is_algorithm_deployed,name='is_algorithm_deployed'),
	url(r'^deploy_algorithm/',views.deploy_algorithm,name='deploy_algorithm'),
	url(r'^redeploy_algorithm/',views.redeploy_algorithm,name='redeploy_algorithm'),
	url(r'^redeploy_algorithm_internal/',csrf_exempt(views.redeploy_algorithm_internal),name='redeploy_algorithm_internal'),
	url(r'^deploy_algorithm_multi/',views.deploy_algorithm_multi,name='deploy_algorithm_multi'),
	url(r'^force_stop/',views.force_stop,name='force_stop'),
	url(r'^stop_waiting_algos/',views.stop_waiting_algos,name='stop_waiting_algos'),
	url(r'^backtests/',views.backtest,name='backtest'),
	url(r'^backtest/',views.backtest,name='backtest'),
	url(r'^sample_backtest/',views.clone_sample_backtest,name='sample_backtest'),
	url(r'^cloned/',views.clone_sample_backtest,name='cloned_backtest'),
	# url(r'^backtest_shared/',views.backtest_shared,name='backtest_shared'),
	url(r'^auto_save_backtest_pref/',views.auto_save_backtest_pref,name='auto_save_backtest_pref'),
	url(r'^get_backtest_pref/',views.get_backtest_pref,name='get_backtest_pref'),
	url(r'^order_log/',views.order_log,name='orders_log'),
	url(r'^orderbook/',views.order_book,name='orderbook'),
	url(r'^mobile_orderbook/',views.mobile_order_book,name='mobile_orderbook'),
	url(r'^fetch_order_book/',views.fetch_order_book,name='fetch_order_book'),
	url(r'^alerts/',views.alerts,name='alerts'),
	url(r'^mobile_alerts/',views.mobile_alerts,name='mobile_alerts'),
	url(r'^fetch_order_log/',views.fetch_order_log,name='fetch_order_log'),
	url(r'^fetch_single_backtest/',views.fetch_single_backtest,name='fetch_single_backtest'),
	url(r'^autocomplete/',views.autocomplete,name='autocomplete'),
	url(r'^autocomplete_indicators/',views.autocomplete_indicators,name='autocomplete_indicators'),
	url(r'^autocomplete_indicators2/',views.autocomplete_indicators2,name='autocomplete_indicators2'),
	url(r'^loadautocomplete/',views.load_autocomplete_data,name='loadautocomplete'),
	url(r'^update_preference/',csrf_exempt(views.update_preference2),name='update_preference'),
	url(r'^load_preference/',views.load_preference2,name='load_preference'),
	url(r'^submit_algorithm/',views.submit_algorithm,name='submit_algorithm'),
	url(r'^get_positions/',views.get_positions,name='get_positions'),

	url(r'^login/',csrf_exempt(views.dummy_login),name='dummy_login'),
	# url(r'^/',views.dummy_login,name='login'),
	url(r'^broker_login/',views.broker_login,name='broker_login'),
	url(r'^broker_login/',views.broker_login,name='login'),
	url(r'^broker_login_url/',views.broker_login_url,name='broker_login_url'),
	url(r'^logout/',views.direct_logout,name='logout'),
	url(r'^register_partner/',views.register_partner,name='register_partner'),

	url(r'^exit_with_positions_open/',views.exit_with_positions_open,name='exit_with_positions_open'),
	url(r'^fetch_open_positions/',views.fetch_open_positions,name='fetch_open_positions'),
	url(r'^fetch_sym_tokens/',views.fetch_sym_tokens,name='fetch_sym_tokens'),
	url(r'^fetch_sym_tokens2/',views.fetch_sym_tokens2,name='fetch_sym_tokens2'),
	url(r'^fetch_id/',views.fetch_id,name='fetch_id'),
	url(r'^exit_position_now_force_stop/',views.exit_position_now_force_stop,name='exit_position_now_force_stop'),
	url(r'^exit_bo_now_force_stop/',views.exit_bo_now_force_stop,name='exit_bo_now_force_stop'),
	url(r'^exit_all/',views.exit_all,name='exit_all'),
	url(r'^update_usage/',csrf_exempt(views.update_usage),name='update_usage'),
	url(r'^get_subscription_limit/',views.get_subscription_limit,name='get_subscription_limit'),
	url(r'^get_subscription_valid/',views.get_subscription_valid,name='get_subscription_valid'),
	url(r'^get_live_algos/',views.get_live_algos,name='get_live_algos'),
	url(r'^generate_shareable_link/',views.generate_shareable_link,name='generate_shareable_link'),
	url(r'^place_order/',views.place_order_new,name='place_order'),
	url(r'^place_order_discipline/',views.place_order_discipline,name='place_order_discipline'),
	url(r'^place_order_tpsl/',views.place_order_tpsl_new,name='place_order_tpsl'),
	url(r'^place_order_direct/',views.place_order_direct,name='place_order_direct'),
	url(r'^portfolio/',views.portfolio,name='portfolio'),
	url(r'^mobile_portfolio/',views.mobile_portfolio,name='mobile_portfolio'),
	url(r'^myaccount/',views.myaccount,name='myaccount'),
	url(r'^help/',views.help,name='help'),
	url(r'^lead_signup/',views.lead_generation,name='lead_generation'),
	url(r'^save_lead/',csrf_exempt(views.save_lead),name='save_lead'),
	url(r'^join_waitlist/',csrf_exempt(views.join_waitlist),name='join_waitlist'),
	url(r'^save_profile_change/',views.save_profile_change,name='save_profile_change'),
	url(r'^trading_terms/',views.trading_terms,name='trading_terms'),
	url(r'^app_trading_terms/',views.app_trading_terms,name='app_trading_terms'),
	url(r'^terms/',views.terms,name='terms'),
	url(r'^app_terms/',views.app_terms,name='app_terms'),
	url(r'^disclosure/',views.disclosure,name='disclosure'),
	url(r'^app_disclosure/',views.app_disclosure,name='app_disclosure'),
	url(r'^privacy/',views.privacy,name='privacy'),
	url(r'^app_privacy/',views.app_privacy,name='app_privacy'),
	url(r'^milestones/May2018',views.milestones052018,name='milestones052018'),
	url(r'^milestones/July2018',views.milestones072018,name='milestones072018'),
	url(r'^$',views.index,name='home'),
	url(r'^mobile_landing/',RedirectView.as_view(url='/', permanent=True),name='mobile_landing'),
	# url(r'^notifications_handler/',views.notifications_handler,name='notifications_handler'),
	url(r'^notifications_handler/',views.notifications_handler2,name='notifications_handler2'),
	url(r'^notifications_handler2/',views.notifications_handler2,name='notifications_handler2'),
	url(r'^deployed_count/',views.deployed_count,name='deployed_count'),
	url(r'^notifications_count/',views.notifications_count,name='notifications_count'),
	# url(r'^v2/notifications_handler/',views.notifications_handler2,name='notifications_handler2'),
	url(r'^fetch_positions/',views.fetch_positions,name='fetch_positions'),
	url(r'^mark_notification_used/',views.mark_notification_used,name='mark_notification_used'),
	url(r'^mark_notifications_used/',views.mark_notification_used2,name='mark_notification_used2'),
	url(r'^fetch_holdings/',views.fetch_holdings,name='fetch_holdings'),
	url(r'^fetch_specific_position/',views.fetch_specific_position,name='fetch_specific_position'),
	url(r'^fetch_billing/',views.fetch_billing,name='fetch_billing'),
	url(r'^fetch_billing_data/',views.fetch_billing_data,name='fetch_billing_data'),
	url(r'^fetch_billing_status/',views.fetch_billing_status,name='fetch_billing_status'),
	url(r'^cancel_subscription/',views.cancel_subscription,name='cancel_subscription'),
	url(r'^cancel_order_click/',views.cancel_order_click,name='cancel_order_click'),
	url(r'^start_subscription/',views.start_subscription,name='start_subscription'),
	url(r'^show_order_details/',views.show_order_details,name='show_order_details'),
	url(r'^first_login_complete/',views.first_login_complete,name='first_login_complete'),
	url(r'^fetch_samples/',views.fetch_samples,name='fetch_samples'),
	url(r'^market_observer_samples/',views.market_observer_samples,name='market_observer_samples'),
	url(r'^fetch_top_performers/',views.fetch_top_performers,name='fetch_top_performers'),
	url(r'^fetch_dashboard_usage_metrics/',views.fetch_dashboard_usage_metrics,name='fetch_dashboard_usage_metrics'),
	url(r'^market_observer_samples/',views.market_observer_samples,name='market_observer_samples'),
	url(r'^fetch_dashboard_metrics/',views.fetch_dashboard_metrics,name='fetch_dashboard_metrics'),
	url(r'^fetch_alerts_mertics/',views.fetch_alerts_mertics,name='fetch_alerts_mertics'),
	url(r'^fetch_dashboard_funds/',views.fetch_dashboard_funds,name='fetch_dashboard_funds'),
	url(r'^clone_sample/',views.clone_sample,name='clone_sample'),
	url(r'^sample_backtest/',views.clone_sample_backtest,name='clone_sample_backtest'),
	url(r'^user_baskets/',views.user_baskets,name='user_baskets'),
	url(r'^user_preference/',views.user_preference,name='user_preference'),
	url(r'^get_session_status/',views.get_session_status,name='get_session_status'),
	url(r'^gen_csrf/',views.gen_csrf,name='gen_csrf'),
	url(r'^update_web_push_subscription/',csrf_exempt(views.update_web_push_subscription),name='update_web_push_subscription'),
	url(r'^submit_unsubscribe_feedback/',views.submit_unsubscribe_feedback,name='submit_unsubscribe_feedback'),
	url(r'^submit_feedback/',views.submit_feedback,name='submit_feedback'),
	url(r'^get_version/',csrf_exempt(views.get_version),name='get_version'),
	url(r'^get_version4/',csrf_exempt(views.get_version4),name='get_version'),
	#url(r'^whats_new/',csrf_exempt(views.whats_new),name='get_version'),
	# crypto loggin
	# url(r'^login/',csrf_exempt(views.login),name='login'),
	url(r'^signup/',csrf_exempt(views.signup),name='signup'),
	url(r'^forgot_password/',csrf_exempt(views.forgot_password),name='forgot_password'),
	url(r'^reset_password/',csrf_exempt(views.password_reset),name='password_reset'),
	url(r'^change_password/',views.change_password,name='change_password'),
	url(r'^generate_2fa/',views.get_otp_provisioning_uri,name='get_otp_provisioning_uri'),
	url(r'^validate_2fa/',views.intialize_otp,name='intialize_otp'),
	url(r'^login_2fa/',csrf_exempt(views.validate_2fa_login),name='validate_2fa_login'),
	url(r'^verification/',views.verification,name='verification'),
	url(r'^account_activation/',csrf_exempt(views.account_activate),name='account_activate'),
	url(r'^direct_logout/',views.direct_logout,name='direct_logout'),
	url(r'^fetch_parsing_tree/',views.fetch_parsing_tree2,name='fetch_parsing_tree'),
	url(r'^v2/fetch_parsing_tree/',views.fetch_parsing_tree,name='fetch_parsing_tree'),
	url(r'^fetch_trainer_model/',views.fetch_trainer_model,name='fetch_trainer_model'),
	url(r'^fetch_sctrainer_model/',views.fetch_sctrainer_model,name='fetch_sctrainer_model'),
	url(r'^get_pricing/',csrf_exempt(views.get_pricing),name='get_pricing'),
	url(r'^v2/get_pricing/',csrf_exempt(views.get_pricing2),name='get_pricing2'),
	url(r'^get_pricing3/',csrf_exempt(views.get_pricing3),name='get_pricing3'),
	url(r'^get_pricing4/',csrf_exempt(views.get_pricing4),name='get_pricing4'),
	url(r'^get_pricing4_web/',csrf_exempt(views.get_pricing4_web),name='get_pricing4'),
	url(r'^fetch_terms/',views.fetch_terms,name='fetch_terms'),
	url(r'^accept_terms/',views.accept_terms,name='accept_terms'),
	url(r'^backtest_webview/',views.backtest_webview,name='accept_terms'),
	url(r'^generate_otp/',views.generate_otp,name='generate_otp'),
	url(r'^save_phone_number/',views.save_phone_number,name='save_phone_number'),
	url(r'^whats_new/',views.whats_new2,name='whats_new'),
	url(r'^v2/whats_new/',views.whats_new2,name='whats_new'),
	
	url(r'^whats_new3/',views.whats_new3,name='whats_new3'),
	url(r'^fetch_total_index_metrics/',views.fetch_total_index_metrics,name='fetch_total_index_metrics'),
	url(r'^.well-known/apple-app-site-association/',views.apple_app_site_association,name='apple_app_site_association'),
	url(r'^apple-app-site-association/',views.apple_app_site_association,name='apple_app_site_association'),
	url(r'^fetch_total_index_metrics/',views.fetch_total_index_metrics,name='fetch_total_index_metrics'),
	url(r'^cancel_order/',views.cancel_order_click,name='cancel_order'),
	url(r'^whats_new/',views.whats_new2,name='whats_new'),
	url(r'^welcome_algo/$',csrf_exempt(views.welcome_algo),name='welcome_algo'),
	# url(r'^welcome_algo_created/$',views.welcome_algo_created,name='welcome_algo_created'),
	url(r'^initialize_account/$',views.initialize_account2,name='initialize_account'),

	# addition html for iOS
	url(r'^backtest_graph/$',views.backtest_graph,name='backtest_graph'),
	url(r'^chart/$',views.chart,name='chart'),

	# addition for payments
	url(r'^generate_subscription/$',csrf_exempt(views.generate_subscription),name='generate_subscription'),
	url(r'^validate_subscription/$',views.validate_subscription,name='validate_subscription'),
	url(r'^receive_subscribe_receipt/$',views.receive_subscribe_receipt,name='receive_subscribe_receipt'),
	url(r'^subscription_reset/$',csrf_exempt(views.subscription_reset),name='subscription_reset'),
	url(r'^paymentProcess/$',csrf_exempt(views.paymentProcess),name='paymentProcess'),
	url(r'^razorpay_payment_capture_webhook/$',csrf_exempt(views.razorpay_payment_capture_webhook),name='razorpay_payment_capture_webhook'),
	url(r'^paymentCardChange/$',csrf_exempt(views.paymentCardChange),name='paymentCardChange'),
	url(r'^fetch_order_preference/$',views.fetch_order_preference,name='fetch_order_preference'),
	url(r'^fetch_payment_preference/$',views.fetch_payment_preference,name='fetch_payment_preference'),
	url(r'^update_additional_info/$',views.update_additional_info,name='update_additional_info'),
	# screener urls
	url(r'^screener/$',views.screener,name='screener'),
	url(r'^copy_screener/$',views.copy_screener,name='copy_screener'),
	url(r'^my_screeners/$',views.my_screeners,name='my_screeners'),
	url(r'^remove_screener/$',views.remove_screener,name='remove_screener'),
	url(r'^favorite_screener/$',views.favorite_screener,name='favorite_screener'),
	url(r'^reinitialize_session/$',views.reinitialize_session,name='reinitialize_session'),
	url(r'^set_alert/$',views.set_alert_screener,name='set_alert_screener'),
	url(r'^get_alerts/$',views.get_alerts_screener,name='get_alerts_screener'),
	url(r'^get_last_alert/$',views.get_last_alert,name='get_last_alert'),
	url(r'^get_alert_history/$',views.get_screener_alert_history,name='get_screener_alert_history'),
	url(r'^stop_alert/$',views.stop_screener_alert,name='stop_screener_alert'),
	url(r'^fetch_terms_of_service/$',views.fetch_terms_of_service,name='fetch_terms_of_service'),
	url(r'^update_to_ultimate/$',views.update_to_ultimate,name='update_to_ultimate'),
	url(r'^load_screener_to_archive/$',views.load_screener_to_archive,name='load_screener_to_archive'),
	
	# discover urls 
	url(r'^fetch_backtest_chart/$',views.fetch_backtest_chart,name='fetch_backtest_chart'),
	url(r'^fetch_shared_backtest_chart/$',views.fetch_shared_backtest_chart,name='fetch_shared_backtest_chart'),
	url(r'^fetch_marketplace_chart/$',views.fetch_marketplace_chart,name='fetch_marketplace_chart'),
	url(r'^deploy_algorithm_multi2/$',views.deploy_algorithm_multi2,name='deploy_algorithm_multi2'),
	url(r'^clone_published/$',views.clone_published,name='clone_published'),
	url(r'^marketplace/$',csrf_exempt(views.marketplace),name='marketplace'),
	url(r'^subscribe_to_algo/$',views.subscribe_to_algo,name='subscribe_to_algo'),
	url(r'^marketplace_deploy/$',views.marketplace_deploy,name='marketplace_deploy'),
	url(r'^my_subscribed_algos/$',views.my_subscribed_algos,name='my_subscribed_algos'),
	url(r'^submit_for_publication/$',views.submit_for_publication,name='submit_for_publication'),
	url(r'^marketplace_backtest/$',csrf_exempt(views.marketplace_backtest),name='marketplace_backtest'),
	url(r'^dashboard_discover/$',csrf_exempt(views.dashboard_discover),name='dashboard_discover'),
	url(r'^discover_watch_list/$',views.discover_watch_list,name='discover_watch_list'),
	url(r'^update_session/$',views.update_session,name='update_session'),
	url(r'^user_version_pref/$',views.user_version_pref,name='user_version_pref'),
	url(r'^user_version_pref_switch/$',views.user_version_pref_switch,name='user_version_pref_switch'),

	# auto save some data to v3 transition
	url(r'^save_redirect/$',views.save_redirect,name='save_redirect'),
	#new marketwatch api
	url(r'^market_watch/$',views.market_watch_new,name='market_watch'),
	url(r'^v2/market_watch/$',views.market_watch_new,name='market_watch_new'),
	url(r'^clone_shared/',views.clone_shared,name='clone_shared'),
	url(r'^backtest_shared/',views.fast_backtest_shared,name='backtest_shared'),

	# dashboardv4 urls 
	url(r'^get_top_movers/$',views.get_top_movers,name='get_top_movers'), 
	url(r'^partial_complete/$',views.partial_complete,name='partial_complete'), 

	# community interactions 
	url(r'^publication_action/$',views.publication_action,name='publication_action'), 
	url(r'^dashboard_recommendations/$',views.dashboard_recommendations,name='dashboard_recommendations'),
	url(r'^dashboard_carousel/$',views.dashboard_carousel,name='dashboard_carousel'),
	url(r'^profile_carousel/$',views.profile_carousel,name='profile_carousel'),

	# ams api's
	url(r'^ams_login/$',csrf_exempt(views.ams_login),name='ams_login'),
	url(r'^ams_sso_login/$',csrf_exempt(views.ams_sso_login),name='ams_login'),
	url(r'^broker_sso_login/$',csrf_exempt(views.ams_generic_sso),name='broker_sso_login'),
	url(r'^ams_logout/$',views.ams_logout,name='ams_logout'),
	url(r'^ams_add_email/$',views.ams_add_email,name='ams_add_email'),

	# new direct email login
	url(r'^forgot_password/',csrf_exempt(views.forgot_password),name='forgot_password'),
	url(r'^reset_password/',csrf_exempt(views.password_reset),name='password_reset'),
	url(r'^change_password/',views.change_password,name='change_password'),
	url(r'^generate_2fa/',views.get_otp_provisioning_uri,name='get_otp_provisioning_uri'),
	url(r'^validate_2fa/',views.intialize_otp,name='intialize_otp'),
	url(r'^login_2fa/',csrf_exempt(views.validate_2fa_login),name='validate_2fa_login'),
	url(r'^user_login/',csrf_exempt(views.user_login),name='user_login'),
	url(r'^validate_email/',csrf_exempt(views.validate_email),name='validate_email'),
	url(r'^verification/',views.verification,name='verification'),
	url(r'^account_activation/',csrf_exempt(views.account_activate),name='account_activate'),

	# referrals apis
	url(r'^sync_contacts/$',views.sync_contacts,name='sync_contacts'),
	url(r'^avail_reward/$',views.avail_reward,name='avail_reward'),
	url(r'^get_all_referrals/$',views.get_all_referrals,name='get_all_referrals'),

	# new v4 web apis
	url(r'^deployed_count2/',views.deployed_count2,name='deployed_count2'),
	url(r'^marketplace_tags/',views.marketplace_tags,name='marketplace_tags'),
	url(r'^screener_tags/',views.screener_tags,name='screener_tags'),
	url(r'^save_backtest_params/$',views.save_backtest_params,name='save_backtest_params'),
]
